//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


	public class ItemStats
	{
		int attackMod{ get; set; }
		int healthMod { get; set; }
		
		public ItemStats(int am, int hm)
		{
			attackMod = am;
			healthMod = hm;
		}
		
		public static ItemStats addStats(IList<Item> items)
		{
			int am = 0;
			int hm = 0;
			
			foreach(Item item in items)
			{
				am += item.getStats().attackMod;
				hm += item.getStats().healthMod;
			}
			return new ItemStats(am, hm);
		}
	}	

